name: CI / php
on: [push, pull_request]
jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with: { php-version: '8.2' }
      - run: php -v
      - name: PHP lint
        run: find . -type f -name "*.php" -print0 | xargs -0 -n1 -P4 php -l
