name: Build & Deploy NL-Tees (Laravel)
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, gd, pdo_pgsql, bcmath, curl, fileinfo
          tools: composer:v2
          coverage: none

      - name: Composer install (prod)
        run: composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: NPM ci & build
        run: |
          npm ci
          npm run build

      - name: App artifacts
        run: |
          mkdir -p deploy
          rsync -a \
            --exclude=".git" \
            --exclude="node_modules" \
            --exclude="tests" \
            --exclude=".github" \
            --exclude="storage/logs/*" \
            --exclude="storage/framework/cache/*" \
            --exclude="storage/framework/sessions/*" \
            --exclude="storage/framework/views/*" \
            ./ deploy/current/
          printf "%s" "${{ secrets.ENV_PROD }}" > deploy/current/.env

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Rsync to server
        run: |
          rsync -az --delete \
            -e "ssh -p ${{ secrets.SSH_PORT }}" \
            deploy/current/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}/current/

      - name: Post-deploy (remote)
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'SSH'
          set -e
          cd "${{ secrets.DEPLOY_PATH }}/current"
          php artisan storage:link || true
          chmod -R ug+rw storage bootstrap/cache
          php artisan config:cache
          php artisan route:cache || true
          php artisan view:cache || true
          php artisan migrate --force
          php artisan queue:restart || true
          # sudo systemctl reload php8.3-fpm || true
          SSH
