name: Build & Deploy NL-Tees (Laravel)
on:
  push:
    branches: [ master ]   # not main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, gd, pdo_pgsql, bcmath, curl, fileinfo
          tools: composer:v2

      - name: Composer install (prod)
        run: composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build assets
        run: |
          npm ci
          npm run build

      - name: Stage artifacts
        run: |
          mkdir -p deploy/current
          rsync -a \
            --exclude=".git" \
            --exclude="node_modules" \
            --exclude="tests" \
            --exclude=".github" \
            --exclude="storage/logs/*" \
            --exclude="storage/framework/cache/*" \
            --exclude="storage/framework/sessions/*" \
            --exclude="storage/framework/views/*" \
            ./ deploy/current/
          printf "%s" "${{ secrets.ENV_PROD }}" > deploy/current/.env

      - name: SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Rsync to shared host
        run: |
          rsync -az --delete \
            -e "ssh -p ${{ secrets.SSH_PORT }}" \
            deploy/current/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}/current/

      - name: Post-deploy (artisan)
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'SSH'
          set -e
          cd "${{ secrets.DEPLOY_PATH }}/current"
          # Adjust php path if needed: /usr/bin/php or /opt/alt/php83/usr/bin/php
          PHP_BIN=${PHP_BIN:-php}
          $PHP_BIN artisan storage:link || true
          $PHP_BIN artisan config:cache
          $PHP_BIN artisan route:cache || true
          $PHP_BIN artisan view:cache || true
          $PHP_BIN artisan migrate --force || true
          SSH
